# Copyright 2014 Google Inc. All rights reserved.
# 
# 	Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Google Deployment Manager template for creating a todo tracker deployment in a project
# Usage:
# $ gcloud components update
# $ gcloud components update preview
# $ gcloud preview deployment-manager templates create todo_tracks_template --template-file config/gce.yaml
# $ gcloud preview deployment-manager deployments --region=us-central1 create --template=todo_tracks_template todo_tracks_deployment
name: todo-tracks
modules:
  network:
    type: NETWORK
    networkModule:
      IPv4Range: "10.240.0.0/16"
      description: "Network for app"
  firewall:
    type: FIREWALL
    firewallModule:
      network: "network"
      sourceRanges: [ "0.0.0.0/0" ]
      allowed:
        - IPProtocol: "tcp"
          ports: ["22", "80", "8443", "8080"]
  todo:
    type: REPLICA_POOL
    replicaPoolModule:
      numReplicas: 1
      replicaPoolParams:
        v1beta1:
          baseInstanceName: "todos-instance"
          machineType: "n1-standard-1"
          zone: "us-central1-a"
          onHostMaintenance: TERMINATE
          networkInterfaces:
            - network: "network"
              accessConfigs:
                - name: External NAT
                  type: ONE_TO_ONE_NAT
          serviceAccounts:
            - email: default
              scopes: [
                "https://www.googleapis.com/auth/cloud-platform",
              ]
          autoRestart: true
          initAction: install-todo
          disksToCreate:
            - boot: true
              autoDelete: true
              initializeParams:
                sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20140828
                diskSizeGb: 50

actions:
  install-todo:
    commands: [
      # First set up the VM to have the appropriate pre-requisites
      #   Install git from backport, base wheezy git is 1.7.x which isn't
      "apt-get -qqy update",
      "apt-get -qqy -t wheezy-backports install git",

      #   Update gcloud to have the preview components (which includes deployment-manager)
      "gcloud --quiet components update",
      "gcloud --quiet components update preview",

      # Finally, copy over todo binary from Google Cloud Storage bucket, and set it up.
      "mkdir -p /bin && wget http://storage.googleapis.com/todo-track-bin/todos -O /bin/todos",
      #   Set executable bit on todo binary.
      "chmod +x /bin/todos",
      "%file:gce.sh",
    ]
